---
  - hosts: all
    become: true
    tasks:
     - name: Update Pack
       ansible.builtin.apt:
        update_cashe: true
     - name: install packages
      ansible.builtin.apt:
        name:
          - htop
          - git
          - vim-nox

